- src/protocols.csv
- src/protocols.js
- test/convert.spec.js
- test/index.spec.js
> rename websockets to ws

- README.md
- package.json
- src/index.js
- test/index.spec.js
Needed in https://github.com/libp2p/js-peer-info/pull/16
> Add isMultiaddr

- src/protocols.csv
The onion size is 96: the address 80 and the port number 16 combined. This is what it says in [multiformats/multiaddr's list](https://github.com/multiformats/multiaddr/blob/master/protocols.csv#L13), and [here](https://github.com/multiformats/go-multiaddr/pull/21#issuecomment-236542881) See https://github.com/multiformats/go-multiaddr/pull/21/commits/e32e9cd0f04503aea903905970d9886fd78da524
> Adjust onion address size to 96

- src/index.js
- test/index.spec.js
* Throws if `addr` is falsy value such as `0`, `false` or `NaN`
* Allows if `null`, `undefined`, `''`
> Tighten validation on addr when creating from existing address

- src/index.js
trying to fix https://github.com/ipfs/js-ipfs/issues/1131 properly.
cc @diasdavid 
Signed-off-by: Yahya <ya7yaz@gmail.com>
> avoid constructor.name pattern

- src/index.js
Quoting @dignifiedquire: "there is a reason we don‘t use instanceof anywhere. It breaks for consumers using the library if they bundle a different set of code or the class."
Reverts multiformats/js-multiaddr#55
> Revert "avoid constructor.name pattern"

- src/convert.js
- src/protocols-table.js
Let's keep 53 reserved for any future /dns protocol. (see multiformats/multiaddr#61). This change is still fine to make at present, because we don't really send these /dnsaddr addresses over the wire anywhere. From what I can tell, there only used in some bootstrap configs.
This change can just go out with the next release any time soon, no particular urgency.
> fix: use consistent /dnsaddr code

- package.json
- src/index.js
This is an ongoing effort to fix the https://github.com/ipfs/js-ipfs/issues/938 issue.
It uses a module I've published that abstracts this solution: https://github.com/ipfs/js-ipfs/issues/1131#issuecomment-373299739.
> feat: use class-is module for type checks

- package.json
- src/convert.js
- test/convert.spec.js
The PR here addresses ip validation issue with ip based js multiaddr #58. 
The existing behavior translates invalid ip addresses to valid ip addresses, and throws on some invalid ip addresses, but not all. 
This patch includes ip-address package which is already apart of js-libp2p-switch to validate ip addresses prior to translating them to and from String to Buffer.
> Add ip validations to ip addr formats

- src/index.js
- test/index.spec.js
Aiming to support the `js-ipfs-api` to connect with a node using a `DNS` multiaddr, I created this PR. Basically, as the API uses the [nodeAddress](https://github.com/ipfs/js-ipfs-api/blob/master/src/index.js#L12) function, it must support all types of address, instead of supporting only thin waist addresses.
Closes https://github.com/ipfs/js-ipfs-api/issues/712
> feat: Add support for multiaddr node with dns

- README.md
- src/convert.js
- src/index.js
- src/protocols-table.js
- test/index.spec.js
- test/protocols.spec.js
> fix UDP code

- src/protocols-table.js
- test/index.spec.js
This is needed so that we can switch to using `p2p` instead of `ipfs` by default.
Replaces #69, this just rebases that and updates tests from the latest master changes.
Closes #68.
> Add p2p protocol support

- src/protocols-table.js
- test/index.spec.js
This corrects an issue with the order of the protocol table. Previously p2p was set last in the order, which caused all created multiaddr's to use p2p instead of ipfs. While `p2p` is the desired protocol name, this helps better support legacy systems that will not yet have support for p2p.
Eventually, `p2p` should be transitioned to the default.
I've updated the test suite to account for p2p and ipfs protocol checks. They verify that created multiaddr's will always use ipfs instead of p2p.
Reference https://github.com/multiformats/js-multiaddr/pull/76#issuecomment-447945684
> fix: make ipfs the default 421 proto name

- src/protocols-table.js
This is part of the endeavor to replace ws-star with the newly created stardust protocol. See libp2p/js-libp2p-websocket-star#70 for a reference
> feat: Add /p2p-stardust

- README.md
- package.json
I think it would make sense to hand the lead maintainership over to someone from the libp2p team, I propose @jacobheun.
What do you think @victorb?
Once approved my @victorb (current lead maintainer) and @daviddias (tech lead) I'll add jacob as maintainer to npm and will remove myself.
> chore: Make @jacobheun the lead maintainer

- examples/try.js
- src/index.js
- test/index.spec.js
There are no longer any references to fromStupidString in the multiaddr and go-multiaddr repos, and it's always been a needlesly inflamtory method name.
This PR remove is and the test that checked it was unimplemented.
There are efforts to provide encoding and decoding between multiaddrs and uris in
- https://github.com/tableflip/multiaddr-to-uri
- https://github.com/tableflip/uri-to-multiaddr
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
> chore: remove unimplemented fromStupidString

- README.md
The ToC points to readme sections that are not longer there.
> docs: Remove broken api links from ToC

- src/codec.js
- src/convert.js
- src/index.js
- src/protocols-table.js
- test/index.spec.js
This also updates the protocol table to match the latest at [multiaddr/protocols.csv](https://github.com/multiformats/multiaddr/blob/f3bb08e27b81523d1f1f0371eb1800395b98922d/protocols.csv)
resolves https://github.com/multiformats/js-multiaddr/issues/82
> add unix protocol support

- src/index.js
- test/index.spec.js
Fix for #54
Adds a test case, and simply reuses the `toString` implementation.
> fix: JSON round trip works as expected

- src/index.js
- test/index.spec.js
Currently `getPeerId` returns the first PeerId in the multiaddr. For most addresses this is fine. However, if a node is using a relay as an entrypoint, such as nodes running AutoRelay, getPeerId returns the id of the relay and not the destination peer.
For example the multiaddr, `/ip4/0.0.0.0/tcp/8080/p2p/QmRelay/p2p-circuit/p2p/QmTarget`, indicates that the target peer `QmTarget` is dialable over the relay peer `QmRelay`. Running `getPeerId` resolves `QmRelay` instead of `QmTarget`. The last peer id in the address should always be the target peer.
> fix: make getPeerId resolve the last id

- package.json
- src/index.js
- test/index.spec.js
While `resolve` is still not yet implemented, this migrates the function away from callbacks. Multiaddr needs a major version release due to #87 changing ports from strings to numbers. While most JS implementations shouldn't have issues, test suites might, and Typescript implementations probably will. As such, I wanted to get this update in that release. While nobody should be using this function as it's not yet implemented, migrating away from callbacks is still technically a breaking change. Once it's implemented, it can just be a minor version update.
When implemented, the function will need to be async and should return a list of multiaddrs, so the footprint won't need to change.
> refactor: use async instead of callbacks

- src/protocols-table.js
- test/index.spec.js
This migrates to using p2p over ipfs as the default text representation of code 421. ipfs will still be supported, but p2p will become the default.
Implementations using multiaddr <= 6.0.0 (Before December 17, 2018) won't be able to parse the p2p text representation.
I am targeting to release this in a 7.0.0 update, which should help with clarity of the rollout. 
Reference https://github.com/libp2p/libp2p/issues/79#issuecomment-514414348
> refactor: default 421 to use p2p by default instead of ipfs

- src/index.js
- test/index.spec.js
This allows users to remove the last index of a given protocol code. It behaves like decapsulate, but checks protocol codes rather than string matching the whole multiaddr.
Unlike `decapsulate`, `decapsulateCode` will not throw when the code isn't present, it just returns the original address, because "I did what you asked" is better than "OMG I couldn't find it!!!".
It's often the case in Libp2p that we want to encapsulate/decapsulate the PeerId in a Multiaddr. This makes it easier to avoid validation problems when using `mafmt`.
For example, let's say there is a peer at `/ip4/127.0.0.1/4001`, with an id of `QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSupNKC`. 
Encapsulated they yield, `/ip4/127.0.0.1/4001/p2p/QmcgpsyWgH8Y8ajJz1Cu72KnS5uo2Aa2LpzU7kinSupNKC`.
If i do a validation check for …
> feat: add decapsulateCode method

- src/index.js
`addr` parameter for `fromNodeAddress`should not be `String` as it accepts an Object.
But maybe I should put `{family: String, address: String, port: Number}` instead?
> Fix jsdoc for `fromNodeAddress`

- package.json
- src/index.js
- test/index.spec.js
This PR implements `Stage 1: Parse CIDs as peer ID` from https://github.com/libp2p/specs/issues/216. 
**TL;DR** This PR does not change the format returned by `getPeerId()`, all we do in `Stage 1` is adding support for Peer IDs represented with CIDs in text form.  
For a wider context see [libp2p/specs/RFC/0001-text-peerid-cid.md](https://github.com/libp2p/specs/blob/master/RFC/0001-text-peerid-cid.md), short story is that CID support will enable IPFS project to support `/ipns/{cid}` in Base32 (https://github.com/ipfs/ipfs/issues/337), enabling things like `http://{libp2p-key-as-cidv1b32}.ipns.dweb.link`
This PR modifies `getPeerId()` to add support for Peer IDs as CIDs.
([libp2p RFC 0001](https://github.com/libp2p/specs/blob/master/RFC/0001-text-peerid-cid.md))
- We need this released, …
> feat: multiaddr support Peer ID represented as CID

- .gitignore
- src/convert.js
- test/index.spec.js
While working on the libp2p refactor tests I found an issue with https://github.com/multiformats/js-multiaddr/pull/102, where if a base32 id contains non b58 characters (such as "l"), b58 would throw due to the unsupported character. This fixes that by getting the b58 string from the CID before decoding to a Buffer.
> fix: ensure b58 can decode hash

- src/index.js
> fix: Inspect deprecation warning

- src/index.d.ts
- src/index.js
- test/index.spec.js
- test/types.spec.ts
- tsconfig.json
This fixes some issues with typings and adds a test that checks whether we export the types correctly.
It also includes all installed `@types/...` types instead of having a manual configuration. See https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types for more information.
> Fix typings and add type test

- src/codec.js
- src/protocols-table.js
This rule is on its way into the latest Standard ☺️
ref: https://github.com/standard/eslint-config-standard/pull/166
Compatibility: Since the code is transpired by aegir this should be compatible ✅
> Use object shorthand for properties

- .aegir.js
- README.md
- examples/try.js
- intro.md
- package.json
- src/codec.js
- src/convert.js
- src/index.d.ts
- src/index.js
- src/ip.js
- test/codec.spec.js
- test/convert.spec.js
- test/index.spec.js
- test/protocols.spec.js
All uses of node Buffers have been replaced with Uint8Arrays.
Also redundant modules have been removed from package.json
BREAKING CHANGES:
- Where node Buffers were returned, now Uint8Arrays are
- The `.buffer` property has been renamed `.bytes` similar to cid@1.0.0
> fix: replace node buffers with uint8arrays

- README.md
afaik aegir no longer produces non-minified production bundle, so the second link is broken
> chore(readme): cleanup browser tag section

- .travis.yml
- README.md
- package.json
- src/index.d.ts
- src/index.js
- src/resolvers/dns.browser.js
- src/resolvers/dns.js
- src/resolvers/index.js
- test/resolvers.spec.js
This PR adds the resolve API method to multiaddr, as well as a custom resolver for `dnsaddr` that `multiaddr` users can rely on. Further custom resolvers including `dns4` and `dns6` should be added to this repo.
Needs:
Closes #94
> feat: resolve multiaddrs

- src/resolvers/dns.js
For some bundlers (example: parcel), `require('dns')` returns `{}`, which would mean the dns exported implementation was null. This throws an error in that case, so that the fallback implementation is used.
> fix: dns require

- tsconfig.json
You can't have trailing commas like this in JSON.
Fixes error `Unexpected token } in JSON at position 458` when trying
to run `npm run build`.
> chore: make tsconfig valid json

- package.json
Silences this sort of warning which [people report as an error](https://github.com/ipfs/js-ipfs/issues/3441):
```
98% after emitting CopyPlugin
WARNING  Compiled with 1 warning                                         21:06:05
warning  in ./node_modules/multiaddr/src/resolvers/dns.js
Module not found: Error: Can't resolve 'dns' in '/home/david/dev/group/node_modules/multiaddr/src/resolvers'
```
Closes #156
> fix: tell bundlers to return false for node dns module

- src/convert.js
- test/convert.spec.js
Supersedes #146. Just adds a test that fails without a fix from @tuyennhv
> Support buffer with any byteOffset values instead of 0

- package.json
- src/convert.js
- src/index.js
- src/ip.js
- test/index.spec.js
Replaces cids and multibase with the new multiformats module.
BREAKING CHANGE: uses the CID class from the new multiformats module
> chore: update to new multiformats

- src/index.ts
Adds return type that constrains family to 4 or 6
> fix: add return to toOptions

- src/index.ts
Give a hint to tsc that the value is a multiaddr.
> fix: infer type after isMultiaddr call

- src/index.ts
Just use the symbol check instead
> fix: remove instanceof from multiaddr check

- package.json
I'd like to convert multiaddr segments to / from bytes in a library that can create multiaddrs.
Creating a full multiaddr wouldn't make sense, nor would reimplementing the conversion logic if it already exists in this library.
Before the ESM version of this library I used multiaddrs/src/convert directly.
See usage of `muConvert` here https://github.com/ChainSafe/discv5/blob/master/src/enr/enr.ts
> feat: add convert subpath export

- src/index.ts
- test/index.spec.ts
When calling toOptions with a dns4 multiaddress, a MultiaddrObject is returned where the ip family is 6 instead of 4. This causes an issue where libp2p is unable to resolve the domain and dial the peer. This only appears to be an issue on some systems. It works on Mac OS but fails on for example Alpine Linux.
Example:
```javascript
const {multiaddr} = require("multiaddr")
console.log(multiaddr('/dns4/google.net/tcp/8000').toOptions())`
```
```javascript
Object {family: 6, host: "google.net", transport: "tcp", port: 8000}
```
> fix: return correct family from toOptions with dns4 MultiAddr

- src/index.ts
Let one method parse the multiaddr details and call it from the other.
> fix: dedupe toOptions/nodeAddress code

- src/convert.ts
- src/ip.ts
- test/ip.spec.ts
Remove leading and training spaces, also adds tests.
> fix: trim string before parsing IP address

- src/protocols-table.ts
- test/index.spec.ts
This adds the webtransport protocol here
> feat: Add webtransport component

- README.md
- src/index.ts
- test/index.spec.ts
- test/resolvers.spec.ts
- Renames the `Multiaddr` class to `DefaultMultiaddr`
- Exports `Multiaddr` as an interface
The `multiaddr` function (introduced in v9.0.0) should be used to create new instances of `Multiaddr` instead of instantiating the `Multiaddr` class directly.
This allows us to remove the `inspect` symbol from the interface and avoid use of `Object.defineProperty` which is very slow:
Fixes: #202
BREAKING CHANGE: the `Multiaddr` class is now an interface
> feat!: convert to interface

- src/convert.ts
- src/ip.ts
Partial fix for the issues observed in the ipfs interop suite - windows seems to lose it's reference to the `results` variable during node startup, but only windows.  Instead return the result from the scope in which is is created.
A follow up will be needed to address the other windows problem which is the IP detection regex seems to stop working.  Might be a bug in node I guess?
> fix: fix converting strings to IP addresses and back again

- test/index.spec.ts
This PR adds tests for real-world  example of webtransport addr announced by Kubo 0.16.0-rc1 (with two certhashes).
> test: webtransport with certhash

- src/index.ts
To make them non-enumerable in a performant way, use private class fields.
> fix: use private class field to store cached strings and tuples

- package.json
See https://github.com/ChainSafe/is-ip/pull/1#issuecomment-1295761316
New version of `@chainsafe/is-ip` provides a node-specific export and faster base implementation.
This library unaffected by the breaking change
> deps: update @chainsafe/is-ip

- src/codec.ts
- src/index.ts
The types for varint were updated, now the `.bytes` property on `varint.decode` can be undefined.
> fix: varint.decode.bytes can now be undefined according to types

- README.md
- package.json
Update project config to include the minified bundle.
> fix: include minified bundle in npm tarball

- README.md
- src/index.ts
- test/index.spec.ts
Simplify the `inspect` output to just contain the string representation of the multiaddr similar to the CID class.
> fix: update inspect format to be like CID class

- src/protocols-table.ts
- test/index.spec.ts
This PR adds support for `/quic-v1` which will be enabled by default in Kubo 0.18 (https://github.com/ipfs/kubo/issues/9417, https://github.com/ipfs/kubo/issues/9410).
@achingbrain @tinytb FYSA an important caveat is that WebTransport addrs will be  `/quic-v1/webtransport`
(as noted in https://github.com/ipfs/kubo/issues/9410).
Ref.
- https://github.com/ipfs/kubo/issues/9410
- https://github.com/multiformats/multiaddr/issues/145
> feat: support /quic-v1

- src/convert.ts
- src/index.ts
- test/index.spec.ts
Hi! This PR is not yet ready to merge. Some questions need to be clarified. Please look.
- Should be the same test data used here as in [go-multiaddr](https://github.com/multiformats/go-multiaddr/blob/master/multiaddr_test.go#L107)? Or better add more test data?
- Should [Multiaddr.nodeAddress](https://github.com/multiformats/js-multiaddr/blob/master/src/index.ts#L449) also support 'ip6zone'? Currently it will throw on any address with 'ip6zone'.
The specs PR is multiformats/multiaddr#68 for reference.
> feat: support ip6zone

- src/protocols-table.ts
- test/index.spec.ts
This allows the construction of `/tls/ws` which is identical and preferred to `/wss`. Similar with `/http`
> feat: add TLS to protocols-table

- src/protocols-table.ts
Adds a new protocol called `webrtc-direct` for enabling webrtc browser-to-browser. https://github.com/libp2p/specs/pull/497
> feat: Add webrtc-w3c protocol for browser to browser

- src/convert.ts
- src/protocols-table.ts
- test/index.spec.ts
Adds the JS part of https://github.com/multiformats/multiaddr/pull/138
> feat: Add SNI support

- src/resolvers/index.ts
- test/resolvers.spec.ts
There's currently a bad txt record in the libp2p bootstrap DNS record so filter out anything that's not in the correct format.
> fix: survive bad dns record

- package.json
- src/index.ts
Related: https://github.com/libp2p/js-libp2p/issues/1269
- deps: install @libp2p/interfaces
- fix: replace err-code with CodeError
- deps: remove err-code
> fix: replace err-code with CodeError

- src/index.ts
**Motivation**
- `getPath()` is not cheap so we want to only compute it on first call. See https://github.com/libp2p/js-libp2p-tcp/pull/264#issuecomment-1503473722
**Description**
- Add private field `#path` and cache it on the first `getPath()` call
> fix: only compute path on first getPath() call

- src/codec.ts
- src/index.ts
- test/codec.spec.ts
Taking #329 to its logical extreme, we're able to simplify the codebase (mostly `codec.ts` and its interaction with `DefaultMultiaddr`).
Precalculate a `MultiaddrParts` when constructing a `DefaultMultiaddr`.
`MultiaddrParts` is essentially an object containing all data which is stored in a `DefaultMultiaddr`.
This makes all `DefaultMultiaddr` methods cheap, at the expense of always storing the string, bytes, tuples, stringTuples, and path of the multiaddr.
The two important functions to review are `stringToMultiaddrParts` and `bytesToMultiaddrParts`, which convert untrusted string and bytes into `MultiaddrParts`.
cc @tuyennhv
> fix: precalculate multiaddr parts

- README.md
Looks like the usage in the README is using the old package name
> docs: import from @multiformats/multiaddr

- package.json
- src/codec.ts
- src/convert.ts
It's faster and we use it elsewhere in the stack so save ourselves an extra dependency.
> deps: switch varint for uint8-varint

- src/index.ts
- src/multiaddr.ts
Cosmetic change ahead.
When logging multaddrs in browsers `DefaultMultiaddr` appears in the console.  It's called this to prevent a collision with the `Multiaddr` TypeScript interface name which is the horse leading the cart.
The interfaces are removed at compile time so here we import the interface with a different name, freeing up the `Multiaddr` symbol to be used as the class name which will now appear in the console.
This change is backwards compatible because everything is hidden behind the `multiaddr` factory function.
> fix: use Multiaddr as class name

- package.json
This removes [undici](https://www.npmjs.com/package/undici) as a  peer dependency
> deps: bump dns-over-http-resolver to 3.0.0

- README.md
- package.json
- src/index.ts
- src/multiaddr.ts
- src/resolvers/dns.browser.ts
- src/resolvers/dns.ts
- src/resolvers/dnsaddr.ts
- src/resolvers/index.ts
- test/resolvers.spec.ts
Accept a `DNS` instance from `@multiformats/dns` when resolving DNSADDR addresses.
Gives the user flexibility to control which DNS servers are used to resolve TXT records.
> feat: accept DNS resolver when resolving DNSADDR addresses

- package.json
- src/resolvers/dnsaddr.ts
- test/resolvers.spec.ts
No need to wrap the query in race signal, it supports abort signals.
> fix: remove unused dep

- test/resolvers.spec.ts
Ensure we don't loop forever resolving dns addrs that resolve to themselves.
> chore: add test for never-ending recursion

- src/resolvers/dnsaddr.ts
- test/resolvers.spec.ts
Remove `"` and `'` characters from DNSADDR results as they sometimes appear in DNS records.
> fix: handle quotes in dnsaddr results

- src/convert.ts
- src/protocols-table.ts
- test/index.spec.ts
Depends on https://github.com/multiformats/multiaddr/pull/164.
> feat: add support for http-path

- package.json
- src/multiaddr.ts
- src/resolvers/dnsaddr.ts
- test/resolvers.spec.ts
`CodeError` is going away in the next libp2p release so use a named error instead.
> fix: use named error instead of CodeError

- src/codec.ts
Throw a `ParseError` instead of and `Error`
> fix: use named error when parsing multiaddrs

- src/index.ts
- src/multiaddr.ts
Update the types to express that the `transport` field will only ever be `'tcp'` or `'udp'`.
> fix: constrain options transport to tcp or udp

- src/codec.ts
- src/index.ts
- test/index.spec.ts
Adds methods to create Multiaddr instances from arrays of tuples so it's possible to insert tuples into Multiaddrs without having to stringify/parse them
> feat: add fromTuples and fromStringTuples methods
